// SEVA.GIS crop catalogue. Row = [name, scientific name, search aliases, season]
// Season: K = Kharif (monsoon), R = Rabi (winter), Z = Zaid (summer), P = perennial / multi-season. Combine letters, e.g. "KR".
export type Row = [name: string, sci: string, aliases: string, season: string];

export const CROP_DATA: Record<string, Row[]> = {
  'Cereals': [
    ['Rice', 'Oryza sativa', 'paddy, dhan, chawal, boro', 'KR'],
    ['Wheat', 'Triticum aestivum', 'gehun, bread wheat', 'R'],
    ['Durum wheat', 'Triticum durum', 'macaroni wheat, pasta wheat', 'R'],
    ['Maize', 'Zea mays', 'corn, makka, bhutta', 'KRZ'],
    ['Barley', 'Hordeum vulgare', 'jau', 'R'],
    ['Oats', 'Avena sativa', 'jai', 'R'],
    ['Rye', 'Secale cereale', '', 'R'],
    ['Triticale', 'x Triticosecale', '', 'R'],
    ['Sorghum', 'Sorghum bicolor', 'jowar, milo, cholam', 'KR'],
    ['Pearl millet', 'Pennisetum glaucum', 'bajra, kambu, sajje', 'K'],
    ['Finger millet', 'Eleusine coracana', 'ragi, mandua, nachni', 'K'],
    ['Foxtail millet', 'Setaria italica', 'kangni, korra, thinai', 'K'],
    ['Little millet', 'Panicum sumatrense', 'kutki, samai', 'K'],
    ['Kodo millet', 'Paspalum scrobiculatum', 'kodra, varagu', 'K'],
    ['Barnyard millet', 'Echinochloa frumentacea', 'sanwa, jhangora, kuthiraivali', 'K'],
    ['Proso millet', 'Panicum miliaceum', 'chena, common millet, panivaragu', 'K'],
    ['Browntop millet', 'Urochloa ramosa', 'korale', 'K'],
    ['Fonio', 'Digitaria exilis', '', 'K'],
    ['Teff', 'Eragrostis tef', '', 'K'],
  ],
  'Pseudocereals': [
    ['Quinoa', 'Chenopodium quinoa', '', 'R'],
    ['Buckwheat', 'Fagopyrum esculentum', 'kuttu, ogal', 'K'],
    ['Grain amaranth', 'Amaranthus cruentus', 'rajgira, ramdana, chaulai grain', 'K'],
  ],
  'Pulses': [
    ['Chickpea', 'Cicer arietinum', 'gram, chana, bengal gram, garbanzo', 'R'],
    ['Pigeon pea', 'Cajanus cajan', 'arhar, tur, toor, red gram', 'K'],
    ['Lentil', 'Lens culinaris', 'masoor', 'R'],
    ['Green gram', 'Vigna radiata', 'moong, mung bean', 'KZ'],
    ['Black gram', 'Vigna mungo', 'urad, mash, urd bean', 'KZ'],
    ['Field pea', 'Pisum sativum', 'dry pea, matar, kasuri', 'R'],
    ['Faba bean', 'Vicia faba', 'broad bean, fava, bakla', 'R'],
    ['Cowpea', 'Vigna unguiculata', 'lobia, black-eyed pea, chawli', 'KZ'],
    ['Horse gram', 'Macrotyloma uniflorum', 'kulthi, kulattha, hurali', 'KR'],
    ['Moth bean', 'Vigna aconitifolia', 'matki, moth', 'K'],
    ['Rice bean', 'Vigna umbellata', '', 'K'],
    ['Adzuki bean', 'Vigna angularis', '', 'K'],
    ['Kidney bean', 'Phaseolus vulgaris', 'rajma, common bean, dry bean', 'KR'],
    ['Lima bean', 'Phaseolus lunatus', 'butter bean', 'K'],
    ['Lablab bean', 'Lablab purpureus', 'sem, hyacinth bean, dolichos, avarai', 'KR'],
    ['Grass pea', 'Lathyrus sativus', 'khesari, lathyrus', 'R'],
    ['Lupin', 'Lupinus albus', '', 'R'],
    ['Bambara groundnut', 'Vigna subterranea', '', 'K'],
  ],
  'Oilseeds': [
    ['Soybean', 'Glycine max', 'soya', 'K'],
    ['Groundnut', 'Arachis hypogaea', 'peanut, moongphali, mungfali', 'KRZ'],
    ['Indian mustard', 'Brassica juncea', 'sarson, rai, raya', 'R'],
    ['Toria', 'Brassica rapa', 'lahi, rapeseed', 'R'],
    ['Rapeseed / Canola', 'Brassica napus', 'canola, oilseed rape', 'R'],
    ['Sunflower', 'Helianthus annuus', 'surajmukhi', 'KRZ'],
    ['Sesame', 'Sesamum indicum', 'til, gingelly, simsim', 'KZ'],
    ['Safflower', 'Carthamus tinctorius', 'kusum, kardi', 'R'],
    ['Niger', 'Guizotia abyssinica', 'ramtil, noug', 'K'],
    ['Linseed', 'Linum usitatissimum', 'flax seed, alsi', 'R'],
    ['Castor', 'Ricinus communis', 'arandi, erand', 'K'],
    ['Camelina', 'Camelina sativa', 'false flax', 'R'],
    ['Chia', 'Salvia hispanica', '', 'K'],
  ],
  'Oil trees': [
    ['Oil palm', 'Elaeis guineensis', 'palm oil', 'P'],
    ['Olive', 'Olea europaea', 'zaitoon', 'P'],
  ],
  'Fibre crops': [
    ['Cotton', 'Gossypium hirsutum', 'kapas, narma, bt cotton, lint', 'K'],
    ['Jute', 'Corchorus olitorius', 'pat, tossa jute, white jute', 'K'],
    ['Mesta / Kenaf', 'Hibiscus cannabinus', 'roselle, ambadi, gongura fibre', 'K'],
    ['Flax (fibre)', 'Linum usitatissimum', 'linen flax', 'R'],
    ['Industrial hemp', 'Cannabis sativa', 'hemp (where legal)', 'KZ'],
    ['Sisal', 'Agave sisalana', '', 'P'],
    ['Ramie', 'Boehmeria nivea', 'china grass', 'P'],
    ['Abaca', 'Musa textilis', 'manila hemp', 'P'],
  ],
  'Sugar crops': [
    ['Sugarcane', 'Saccharum officinarum', 'ganna, noble cane', 'P'],
    ['Sugar beet', 'Beta vulgaris', 'chukandar sugar', 'R'],
    ['Sweet sorghum', 'Sorghum bicolor', 'sweet stalk', 'K'],
    ['Stevia', 'Stevia rebaudiana', 'sweet leaf', 'P'],
  ],
  'Roots & Tubers': [
    ['Potato', 'Solanum tuberosum', 'aloo, batata', 'R'],
    ['Sweet potato', 'Ipomoea batatas', 'shakarkand, ratalu', 'KR'],
    ['Cassava', 'Manihot esculenta', 'tapioca, kappa, yuca, manioc', 'P'],
    ['Yam', 'Dioscorea alata', 'greater yam, ratalu, ube', 'K'],
    ['Elephant foot yam', 'Amorphophallus paeoniifolius', 'suran, jimikand, senai', 'K'],
    ['Taro', 'Colocasia esculenta', 'arbi, colocasia, eddoe, dasheen', 'K'],
    ['Tannia', 'Xanthosoma sagittifolium', 'yautia, cocoyam', 'K'],
    ['Arrowroot', 'Maranta arundinacea', 'koova', 'K'],
  ],
  'Vegetables / Leafy': [
    ['Spinach', 'Spinacia oleracea', 'palak', 'R'],
    ['Amaranth leaves', 'Amaranthus tricolor', 'chaulai, thotakura, cheera', 'KZ'],
    ['Fenugreek leaves', 'Trigonella foenum-graecum', 'methi', 'R'],
    ['Coriander leaves', 'Coriandrum sativum', 'dhania, cilantro', 'R'],
    ['Lettuce', 'Lactuca sativa', 'salad', 'R'],
    ['Mustard greens', 'Brassica juncea', 'sarson saag', 'R'],
    ['Bathua', 'Chenopodium album', 'lambsquarters', 'R'],
    ['Celery', 'Apium graveolens', '', 'R'],
    ['Kale', 'Brassica oleracea var. sabellica', 'haak', 'R'],
    ['Swiss chard', 'Beta vulgaris var. cicla', 'palak beet', 'R'],
  ],
  'Vegetables / Cole crops': [
    ['Cabbage', 'Brassica oleracea var. capitata', 'patta gobhi, band gobhi', 'R'],
    ['Cauliflower', 'Brassica oleracea var. botrytis', 'phool gobhi', 'R'],
    ['Broccoli', 'Brassica oleracea var. italica', '', 'R'],
    ['Kohlrabi', 'Brassica oleracea var. gongylodes', 'knol khol, ganth gobhi', 'R'],
    ['Brussels sprouts', 'Brassica oleracea var. gemmifera', '', 'R'],
    ['Chinese cabbage', 'Brassica rapa var. pekinensis', 'pak choi, bok choy', 'R'],
  ],
  'Vegetables / Fruit vegetables': [
    ['Tomato', 'Solanum lycopersicum', 'tamatar', 'KRZ'],
    ['Brinjal', 'Solanum melongena', 'eggplant, aubergine, baingan, vankaya', 'KRZ'],
    ['Green chilli', 'Capsicum annuum', 'hari mirch, chili pepper', 'KR'],
    ['Capsicum', 'Capsicum annuum var. grossum', 'bell pepper, shimla mirch', 'R'],
    ['Okra', 'Abelmoschus esculentus', 'bhindi, lady finger, gumbo', 'KZ'],
    ['Cucumber', 'Cucumis sativus', 'kheera', 'Z'],
    ['Pumpkin', 'Cucurbita moschata', 'kaddu, sitaphal, squash', 'KZ'],
    ['Zucchini', 'Cucurbita pepo', 'summer squash, courgette', 'R'],
    ['Bottle gourd', 'Lagenaria siceraria', 'lauki, ghiya, doodhi', 'KZ'],
    ['Bitter gourd', 'Momordica charantia', 'karela, bitter melon', 'KZ'],
    ['Ridge gourd', 'Luffa acutangula', 'turai, turia, peerkangai', 'KZ'],
    ['Sponge gourd', 'Luffa aegyptiaca', 'nenua, galka', 'KZ'],
    ['Snake gourd', 'Trichosanthes cucumerina', 'chichinda, padwal', 'K'],
    ['Ash gourd', 'Benincasa hispida', 'petha, winter melon, kushmanda', 'K'],
    ['Pointed gourd', 'Trichosanthes dioica', 'parwal, patol', 'P'],
    ['Ivy gourd', 'Coccinia grandis', 'tindora, kundru, tondli', 'P'],
    ['Round gourd', 'Praecitrullus fistulosus', 'tinda, indian squash', 'Z'],
    ['Chayote', 'Sechium edule', 'chow chow, bangalore brinjal', 'P'],
    ['Sweet corn', 'Zea mays var. saccharata', 'baby corn, bhutta', 'KRZ'],
    ['Drumstick', 'Moringa oleifera', 'moringa, sahjan, murungai', 'P'],
  ],
  'Vegetables / Pod vegetables': [
    ['Garden pea', 'Pisum sativum', 'hara matar, green peas', 'R'],
    ['French bean', 'Phaseolus vulgaris', 'green bean, snap bean, farasbi', 'KR'],
    ['Cluster bean', 'Cyamopsis tetragonoloba', 'guar, gawar, goruchikkudu', 'KZ'],
    ['Yardlong bean', 'Vigna unguiculata subsp. sesquipedalis', 'lobia pods, chawli', 'KZ'],
  ],
  'Vegetables / Root & Bulb': [
    ['Onion', 'Allium cepa', 'pyaz, kanda, dungri', 'KR'],
    ['Garlic', 'Allium sativum', 'lahsun', 'R'],
    ['Leek', 'Allium porrum', '', 'R'],
    ['Carrot', 'Daucus carota', 'gajar', 'R'],
    ['Radish', 'Raphanus sativus', 'mooli, daikon', 'R'],
    ['Beetroot', 'Beta vulgaris', 'chukandar, beet', 'R'],
    ['Turnip', 'Brassica rapa var. rapa', 'shalgam', 'R'],
  ],
  'Fruits / Tropical': [
    ['Mango', 'Mangifera indica', 'aam', 'P'],
    ['Banana', 'Musa x paradisiaca', 'kela, plantain', 'P'],
    ['Papaya', 'Carica papaya', 'papita, pawpaw', 'P'],
    ['Guava', 'Psidium guajava', 'amrud, peru', 'P'],
    ['Pineapple', 'Ananas comosus', 'ananas', 'P'],
    ['Jackfruit', 'Artocarpus heterophyllus', 'kathal, panasa', 'P'],
    ['Litchi', 'Litchi chinensis', 'lychee', 'P'],
    ['Sapota', 'Manilkara zapota', 'chikoo, chiku, sapodilla', 'P'],
    ['Custard apple', 'Annona squamosa', 'sitaphal, sharifa', 'P'],
    ['Pomegranate', 'Punica granatum', 'anar, dalimb', 'P'],
    ['Avocado', 'Persea americana', 'butter fruit', 'P'],
    ['Passion fruit', 'Passiflora edulis', 'krishna phal', 'P'],
    ['Dragon fruit', 'Selenicereus undatus', 'pitaya, pitahaya, kamalam', 'P'],
    ['Date palm', 'Phoenix dactylifera', 'khajoor, dates', 'P'],
    ['Fig', 'Ficus carica', 'anjeer', 'P'],
    ['Jamun', 'Syzygium cumini', 'java plum, black plum', 'P'],
    ['Amla', 'Phyllanthus emblica', 'indian gooseberry, awla', 'P'],
    ['Ber', 'Ziziphus mauritiana', 'indian jujube, indian plum, bor', 'P'],
    ['Bael', 'Aegle marmelos', 'bel, wood apple', 'P'],
    ['Tamarind', 'Tamarindus indica', 'imli', 'P'],
    ['Star fruit', 'Averrhoa carambola', 'carambola, kamrakh', 'P'],
    ['Mulberry', 'Morus alba', 'shahtoot, tut, silkworm mulberry', 'P'],
    ['Durian', 'Durio zibethinus', '', 'P'],
    ['Rambutan', 'Nephelium lappaceum', '', 'P'],
    ['Mangosteen', 'Garcinia mangostana', '', 'P'],
    ['Soursop', 'Annona muricata', 'graviola, hanuman phal', 'P'],
  ],
  'Fruits / Citrus': [
    ['Sweet orange', 'Citrus x sinensis', 'malta, orange', 'P'],
    ['Mosambi', 'Citrus limetta', 'sweet lime, musambi', 'P'],
    ['Mandarin', 'Citrus reticulata', 'santra, kinnow, nagpur orange', 'P'],
    ['Lemon', 'Citrus limon', 'nimbu', 'P'],
    ['Acid lime', 'Citrus aurantiifolia', 'kagzi nimbu, lime', 'P'],
    ['Grapefruit', 'Citrus x paradisi', '', 'P'],
    ['Pomelo', 'Citrus maxima', 'chakotra, shaddock', 'P'],
  ],
  'Fruits / Temperate': [
    ['Apple', 'Malus domestica', 'seb', 'P'],
    ['Pear', 'Pyrus communis', 'nashpati', 'P'],
    ['Peach', 'Prunus persica', 'aadu', 'P'],
    ['Plum', 'Prunus domestica', 'aloo bukhara', 'P'],
    ['Apricot', 'Prunus armeniaca', 'khubani, chuli', 'P'],
    ['Cherry', 'Prunus avium', 'gilas', 'P'],
    ['Persimmon', 'Diospyros kaki', 'japani phal', 'P'],
    ['Quince', 'Cydonia oblonga', 'safarchand', 'P'],
    ['Kiwifruit', 'Actinidia deliciosa', 'kiwi', 'P'],
  ],
  'Fruits / Grapes & Berries': [
    ['Grape', 'Vitis vinifera', 'angoor, draksha', 'P'],
    ['Strawberry', 'Fragaria x ananassa', '', 'R'],
    ['Blueberry', 'Vaccinium corymbosum', '', 'P'],
    ['Raspberry', 'Rubus idaeus', '', 'P'],
    ['Blackberry', 'Rubus fruticosus', '', 'P'],
    ['Cranberry', 'Vaccinium macrocarpon', '', 'P'],
  ],
  'Fruits / Melons': [
    ['Watermelon', 'Citrullus lanatus', 'tarbooz', 'Z'],
    ['Muskmelon', 'Cucumis melo', 'kharbooza, cantaloupe, honeydew', 'Z'],
  ],
  'Nuts': [
    ['Almond', 'Prunus dulcis', 'badam', 'P'],
    ['Walnut', 'Juglans regia', 'akhrot', 'P'],
    ['Cashew', 'Anacardium occidentale', 'kaju', 'P'],
    ['Pistachio', 'Pistacia vera', 'pista', 'P'],
    ['Hazelnut', 'Corylus avellana', 'filbert', 'P'],
    ['Pecan', 'Carya illinoinensis', '', 'P'],
    ['Macadamia', 'Macadamia integrifolia', '', 'P'],
    ['Chestnut', 'Castanea sativa', '', 'P'],
  ],
  'Spices & Condiments': [
    ['Black pepper', 'Piper nigrum', 'kali mirch', 'P'],
    ['Cardamom', 'Elettaria cardamomum', 'elaichi, small cardamom', 'P'],
    ['Turmeric', 'Curcuma longa', 'haldi', 'K'],
    ['Ginger', 'Zingiber officinale', 'adrak, sonth', 'K'],
    ['Dry chilli', 'Capsicum annuum', 'lal mirch, red chilli', 'KR'],
    ['Coriander seed', 'Coriandrum sativum', 'dhania seed', 'R'],
    ['Cumin', 'Cuminum cyminum', 'jeera', 'R'],
    ['Fennel', 'Foeniculum vulgare', 'saunf', 'R'],
    ['Fenugreek seed', 'Trigonella foenum-graecum', 'methi dana', 'R'],
    ['Ajwain', 'Trachyspermum ammi', 'carom, bishop weed', 'R'],
    ['Nigella', 'Nigella sativa', 'kalonji, black cumin', 'R'],
    ['Clove', 'Syzygium aromaticum', 'laung', 'P'],
    ['Cinnamon', 'Cinnamomum verum', 'dalchini', 'P'],
    ['Nutmeg', 'Myristica fragrans', 'jaiphal, mace, javitri', 'P'],
    ['Saffron', 'Crocus sativus', 'kesar', 'P'],
    ['Vanilla', 'Vanilla planifolia', '', 'P'],
    ['Curry leaf', 'Murraya koenigii', 'kadi patta', 'P'],
  ],
  'Plantation & Beverage': [
    ['Tea', 'Camellia sinensis', 'chai', 'P'],
    ['Coffee', 'Coffea arabica', 'arabica, robusta, coffea canephora', 'P'],
    ['Cocoa', 'Theobroma cacao', 'cacao, chocolate', 'P'],
    ['Rubber', 'Hevea brasiliensis', 'natural rubber', 'P'],
    ['Coconut', 'Cocos nucifera', 'nariyal, copra, thengai', 'P'],
    ['Areca nut', 'Areca catechu', 'supari, betel nut', 'P'],
  ],
  'Fodder & Forage': [
    ['Berseem', 'Trifolium alexandrinum', 'egyptian clover', 'R'],
    ['Lucerne', 'Medicago sativa', 'alfalfa, rijka', 'P'],
    ['Fodder maize', 'Zea mays', 'green fodder, silage maize', 'KZ'],
    ['Fodder sorghum', 'Sorghum bicolor', 'chari, sudan grass, sudangrass', 'KZ'],
    ['Fodder oats', 'Avena sativa', 'green oats', 'R'],
    ['Napier grass', 'Pennisetum purpureum', 'hybrid napier, elephant grass', 'P'],
    ['Guinea grass', 'Megathyrsus maximus', 'panicum maximum', 'P'],
    ['Rhodes grass', 'Chloris gayana', '', 'P'],
    ['Dinanath grass', 'Pennisetum pedicellatum', '', 'K'],
    ['Fodder cowpea', 'Vigna unguiculata', 'lobia fodder', 'KZ'],
    ['Ryegrass', 'Lolium multiflorum', 'italian ryegrass', 'R'],
    ['White clover', 'Trifolium repens', '', 'R'],
    ['Vetch', 'Vicia sativa', 'common vetch', 'R'],
    ['Stylo', 'Stylosanthes hamata', '', 'P'],
    ['Subabul', 'Leucaena leucocephala', 'leucaena', 'P'],
    ['Fodder beet', 'Beta vulgaris', 'mangel', 'R'],
  ],
  'Medicinal & Aromatic': [
    ['Aloe vera', 'Aloe vera', 'ghritkumari, kumari', 'P'],
    ['Ashwagandha', 'Withania somnifera', 'indian ginseng, winter cherry', 'K'],
    ['Tulsi', 'Ocimum tenuiflorum', 'holy basil', 'P'],
    ['Mint', 'Mentha arvensis', 'pudina, menthol mint, japanese mint', 'Z'],
    ['Lemongrass', 'Cymbopogon flexuosus', '', 'P'],
    ['Citronella', 'Cymbopogon winterianus', '', 'P'],
    ['Palmarosa', 'Cymbopogon martinii', '', 'P'],
    ['Vetiver', 'Chrysopogon zizanioides', 'khus', 'P'],
    ['Patchouli', 'Pogostemon cablin', '', 'P'],
    ['Isabgol', 'Plantago ovata', 'psyllium, ispaghula', 'R'],
    ['Senna', 'Cassia angustifolia', 'sonamukhi', 'KR'],
    ['Safed musli', 'Chlorophytum borivilianum', '', 'K'],
    ['Geranium', 'Pelargonium graveolens', '', 'P'],
    ['Lavender', 'Lavandula angustifolia', '', 'P'],
    ['Chamomile', 'Matricaria chamomilla', '', 'R'],
    ['Brahmi', 'Bacopa monnieri', '', 'P'],
    ['Kalmegh', 'Andrographis paniculata', 'king of bitters', 'K'],
    ['Giloy', 'Tinospora cordifolia', 'guduchi', 'P'],
  ],
  'Flowers': [
    ['Rose', 'Rosa spp.', 'gulab', 'P'],
    ['Marigold', 'Tagetes erecta', 'genda', 'KRZ'],
    ['Jasmine', 'Jasminum sambac', 'mogra, chameli, mallige', 'P'],
    ['Chrysanthemum', 'Chrysanthemum morifolium', 'guldaudi, shevanti', 'R'],
    ['Gladiolus', 'Gladiolus hybridus', '', 'R'],
    ['Tuberose', 'Polianthes tuberosa', 'rajnigandha', 'P'],
    ['Gerbera', 'Gerbera jamesonii', '', 'P'],
    ['Carnation', 'Dianthus caryophyllus', '', 'P'],
    ['China aster', 'Callistephus chinensis', '', 'R'],
    ['Crossandra', 'Crossandra infundibuliformis', 'kanakambaram, aboli', 'P'],
  ],
  'Industrial & Other': [
    ['Tobacco', 'Nicotiana tabacum', 'tambaku', 'R'],
    ['Hops', 'Humulus lupulus', '', 'P'],
    ['Jatropha', 'Jatropha curcas', 'biodiesel plant', 'P'],
    ['Indigo', 'Indigofera tinctoria', 'neel', 'K'],
    ['Henna', 'Lawsonia inermis', 'mehndi', 'P'],
    ['Agave', 'Agave tequilana', 'blue agave', 'P'],
  ],
  'Agroforestry & Trees': [
    ['Eucalyptus', 'Eucalyptus spp.', 'nilgiri', 'P'],
    ['Teak', 'Tectona grandis', 'sagwan', 'P'],
    ['Poplar', 'Populus deltoides', 'safeda', 'P'],
    ['Bamboo', 'Bambusa spp.', 'baans', 'P'],
    ['Casuarina', 'Casuarina equisetifolia', 'she-oak', 'P'],
    ['Neem', 'Azadirachta indica', 'margosa', 'P'],
    ['Sandalwood', 'Santalum album', 'chandan', 'P'],
  ],
  'Green Manure & Cover Crops': [
    ['Dhaincha', 'Sesbania bispinosa', 'sesbania, sesbania aculeata', 'K'],
    ['Sunn hemp', 'Crotalaria juncea', 'sanai, sann', 'K'],
    ['Azolla', 'Azolla pinnata', 'biofertilizer fern', 'K'],
    ['Cover crop mix', '', 'catch crop, green cover', 'P'],
  ],
  'Land Cover (no crop)': [
    ['Uncultivated land', '', 'fallow, empty field, wasteland, barren, uncropped, abandoned', 'P'],
    ['Bare land', '', 'bare soil, ploughed, tilled, sandy, open ground, dirt', 'P'],
    ['Fallow / bare soil', '', 'empty field, ploughed, tilled, uncultivated, seasonal rest', 'P'],
    ['Mixed / intercrop', '', 'multiple crops, mixed cropping, intercropping, polyculture', 'P'],
    ['Pasture / grassland', '', 'grazing land, meadow, pasture, fodder grass', 'P'],
    ['Mixed orchard', '', 'orchard, multiple fruit trees, agroforestry', 'P'],
    ['Not sure / other', '', 'unknown, custom crop, general agriculture', 'P'],
  ],
};

export const SEASON_LABEL: Record<string, string> = {
  K: 'Kharif (monsoon)', R: 'Rabi (winter)', Z: 'Zaid (summer)', P: 'Perennial / multi-season',
};

export interface Crop {
  id: string; name: string; sci: string; aliases: string; season: string;
  category: string; // full label, e.g. "Vegetables / Leafy"
  group: string;    // top level, e.g. "Vegetables"
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export const CROPS: Crop[] = Object.entries(CROP_DATA).flatMap(([category, rows]) =>
  rows.map(([name, sci, aliases, season]) => ({
    id: `${slug(category)}__${slug(name)}`, name, sci, aliases, season,
    category, group: category.split(' / ')[0],
  })),
);

export const GROUPS: string[] = [...new Set(CROPS.map((c) => c.group))];

/** Search by name, scientific name, local names or category. Empty query returns everything in the group. */
export function searchCrops(query: string, group?: string): Crop[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  const pool = group ? CROPS.filter((c) => c.group === group) : CROPS;
  if (!terms.length) return pool;
  return pool
    .map((c) => {
      const name = c.name.toLowerCase();
      const hay = `${name} ${c.sci.toLowerCase()} ${c.aliases.toLowerCase()} ${c.category.toLowerCase()}`;
      if (!terms.every((t) => hay.includes(t))) return null;
      const score = name === terms.join(' ') ? 0 : name.startsWith(terms[0]) ? 1 : name.includes(terms[0]) ? 2 : 3;
      return { c, score };
    })
    .filter((x): x is { c: Crop; score: number } => x !== null)
    .sort((a, b) => a.score - b.score || a.c.name.localeCompare(b.c.name))
    .map((x) => x.c);
}
